const decisions = [
  ['ADR-001', 'FastAPI backend-for-frontend', 'Protects the vendor API key, validates requests, and gives the browser one stable contract.', 'One additional network hop and a second backend process.'],
  ['ADR-002', 'React, Tailwind, and TanStack Query', 'Provides clear component ownership, responsive styling, and explicit request lifecycle states.', 'A frontend build step and more dependencies than plain JavaScript.'],
  ['ADR-003', 'Bun with Vite', 'Offers fast installs, a quick development loop, and a small static deployment artifact.', 'Contributors need Bun as well as Python for the full stack.'],
  ['ADR-004', 'Separate mock vendor service', 'Exercises the real integration boundary, including authentication, timeouts, and upstream failures.', 'Local development requires an additional service process.'],
  ['ADR-005', 'GitHub Pages with optional demo mode', 'Publishes an interactive static UI while keeping the production API key inside the separately hosted BFF.', 'Pages demo mode uses a client-side calculation and does not replace the live authenticated flow.'],
]

export default function Documentation() {
  return (
    <div className="space-y-16">
      <section>
        <p className="eyebrow-text">Service documentation</p>
        <h1 className="mt-3 max-w-3xl text-5xl font-semibold leading-tight tracking-tight text-white sm:text-6xl">A UI and BFF architecture built for a real vendor boundary.</h1>
        <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">This page explains how the Commission Quote service works, why each technology was selected, and the architectural decisions behind the implementation.</p>
      </section>

      <section aria-labelledby="architecture-title"><div className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow-text">System map</p><h2 id="architecture-title" className="mt-3 text-3xl font-semibold text-white">One request, two trusted boundaries.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">The browser talks to the BFF. Only the BFF can reach the vendor with its private credential.</p></div><div className="architecture-diagram" role="img" aria-label="Browser connects to React UI, React UI connects to FastAPI BFF, and FastAPI BFF connects to the authenticated mock vendor API"><div className="architecture-node"><span className="architecture-kicker">Client</span><strong>Browser</strong><small>Staff workflow</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-accent"><span className="architecture-kicker">Frontend</span><strong>React UI</strong><small>Form + query state</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-accent"><span className="architecture-kicker">BFF :8000</span><strong>FastAPI</strong><small>Validation + secret</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-vendor"><span className="architecture-kicker">Vendor :8001</span><strong>Mock API</strong><small>Quote calculation</small></div></div><p className="mt-4 text-center font-mono text-xs text-slate-500">api-key travels only between FastAPI and the vendor</p></section>

      <section><div className="mb-8"><p className="eyebrow-text">Request flow</p><h2 className="mt-3 text-3xl font-semibold text-white">What happens when a quote is generated?</h2></div><ol className="grid gap-4 md:grid-cols-2"><li className="doc-step"><span>01</span><p>The React form validates the amount, term, and risk band before submitting.</p></li><li className="doc-step"><span>02</span><p>TanStack Query sends <code>POST /api/quotes</code> to the FastAPI BFF and exposes pending, success, and error states.</p></li><li className="doc-step"><span>03</span><p>Pydantic validates the payload again. The BFF keeps the vendor credential server-side.</p></li><li className="doc-step"><span>04</span><p>HTTPX calls the vendor's <code>POST /quotes</code> endpoint with the private <code>api-key</code>.</p></li><li className="doc-step"><span>05</span><p>The vendor authenticates, calculates the quote, and may simulate a <code>503</code> outage.</p></li><li className="doc-step"><span>06</span><p>The BFF maps upstream responses into a stable browser contract and friendly error statuses.</p></li></ol></section>

      <section><div className="mb-8"><p className="eyebrow-text">Layer responsibilities</p><h2 className="mt-3 text-3xl font-semibold text-white">Each layer has one clear job.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['React + Tailwind', 'Form, responsive UI, accessibility, and quote states'], ['TanStack Query', 'Quote mutation lifecycle and server-state handling'], ['FastAPI BFF', 'Public API, validation, secret handling, timeout/error mapping'], ['HTTPX client', 'Outbound vendor request with connection reuse and timeout support'], ['Mock vendor API', 'API-key enforcement, deterministic calculation, random outages'], ['Shared models', 'Pydantic contracts, Decimal calculations, and risk-band rules']].map(([name, description]) => <div className="doc-panel" key={name}><h3>{name}</h3><p>{description}</p></div>)}</div></section>

      <section><div className="mb-8"><p className="eyebrow-text">Non-functional requirements</p><h2 className="mt-3 text-3xl font-semibold text-white">Quality attributes and honest boundaries.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-400">The current controls are intentionally small for this exercise. Production authentication, entitlement enforcement, and operational safeguards are called out rather than implied.</p></div><div className="grid gap-4 md:grid-cols-2">{[['Security', 'Current: BFF-only vendor secret, API-key enforcement, and boundary validation.', 'Next: HTTPS, secret manager, key rotation, and security headers.'], ['Authentication', 'Current: vendor authenticates the BFF with the api-key header.', 'Next: staff identity authentication with OIDC or OAuth2.'], ['Authorization and entitlements', 'Current: not implemented; valid callers can submit quote requests.', 'Next: verified identity, roles, product eligibility, and loan-limit checks.'], ['Availability', 'Current: bounded timeout, health endpoint, and friendly upstream failures.', 'Next: circuit breaker, redundancy, alerting, and retry policy.'], ['Reliability', 'Current: Decimal calculations, contracts, deterministic logic, and tests.', 'Next: real-vendor contract tests, idempotency, and audit records.'], ['Performance', 'Current: HTTPX connection reuse and bounded upstream wait time.', 'Next: latency targets, load tests, rate limiting, and capacity planning.'], ['Observability', 'Current: stable errors, matching correlation IDs, and no secrets exposed to users.', 'Next: structured logs, metrics, distributed tracing, and security audit events.'], ['Accessibility', 'Current: labels, focus styles, responsive UI, loading state, and live regions.', 'Next: WCAG automation and manual assistive-technology testing.']].map(([name, current, next]) => <article className="nfr-card" key={name}><h3>{name}</h3><p>{current}</p><small>{next}</small></article>)}</div></section>

      <section><div className="mb-8"><p className="eyebrow-text">Technology choices</p><h2 className="mt-3 text-3xl font-semibold text-white">Selected for clarity and fit.</h2></div><div className="overflow-x-auto rounded-xl border border-white/10"><table className="doc-table"><thead><tr><th>Technology</th><th>Benefit</th><th>Why not the main alternatives?</th></tr></thead><tbody>{[['React', 'Component boundaries keep form and result states easy to extend.', 'Plain JavaScript becomes harder to organize as screens grow.'], ['Tailwind CSS', 'Fast, consistent responsive styling without a large framework.', 'A component library adds more dependencies than this workflow needs.'], ['TanStack Query', 'Explicit mutation states with a path to retries and caching.', 'Plain fetch offers less structure for future server state.'], ['Bun + Vite', 'Fast installs, quick feedback, and simple static builds.', 'Node works equally well; Bun was selected as the requested alternative runtime.'], ['FastAPI', 'Typed validation, dependency injection, and clear Python APIs.', 'Django is heavier; Flask needs more API structure added manually.'], ['HTTPX', 'Timeouts, connection reuse, and injectable test transports.', 'A lower-level client adds detail without helping this service.']].map(([technology, benefit, alternative]) => <tr key={technology}><td>{technology}</td><td>{benefit}</td><td>{alternative}</td></tr>)}</tbody></table></div></section>

      <section aria-labelledby="adr-title"><div className="mb-8"><p className="eyebrow-text">Architecture decision records</p><h2 id="adr-title" className="mt-3 text-3xl font-semibold text-white">Why this shape?</h2><p className="mt-3 max-w-2xl leading-7 text-slate-400">A typical ADR records status, context, decision, alternatives, benefits, and consequences. These records capture the choices made for this service.</p></div><div className="grid gap-4 md:grid-cols-2">{decisions.map(([id, title, benefit, consequence]) => <article className="adr-card" key={id}><div className="flex items-center justify-between"><span className="adr-id">{id}</span><span className="adr-status">Accepted</span></div><h3>{title}</h3><p>{benefit}</p><small>Consequence: {consequence}</small></article>)}</div></section>
    </div>
  )
}
