import { useMutation } from '@tanstack/react-query'
import { generateQuote } from './api/quotes'
import QuoteForm from './components/QuoteForm'
import QuoteResult from './components/QuoteResult'

export default function App() {
  const quoteMutation = useMutation({ mutationFn: generateQuote, retry: false })
  const isDemo = import.meta.env.VITE_DEMO_MODE === 'true'

  return (
    <main className="min-h-screen px-5 py-8 sm:px-8 lg:px-12">
      <div className="mx-auto max-w-6xl">
        <header className="mb-10 flex items-center justify-between border-b border-white/10 pb-6">
          <div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-amber-300 font-black text-slate-950">CQ</span><span className="text-sm font-semibold tracking-wide text-white">Lending Platform</span></div>
          <span className="text-xs font-medium uppercase tracking-[0.18em] text-slate-500">Staff workspace</span>
        </header>
        <section className="grid gap-8 lg:grid-cols-[0.86fr_1.14fr] lg:items-stretch">
          <div className="py-4 lg:py-14"><p className="mb-5 text-sm font-bold uppercase tracking-[0.25em] text-amber-300">Commission quote</p><h1 className="max-w-xl text-5xl font-semibold leading-[1.04] tracking-tight text-white sm:text-6xl">A clearer view of every loan.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-400">Turn application details into a precise commission estimate, backed by the vendor calculation service.</p><div className="mt-10 flex gap-8 text-sm"><div><p className="font-semibold text-white">01</p><p className="mt-1 text-slate-500">Enter details</p></div><div><p className="font-semibold text-white">02</p><p className="mt-1 text-slate-500">Review quote</p></div></div></div>
          <div className="grid gap-5 rounded-2xl border border-white/10 bg-slate-900/80 p-6 shadow-2xl shadow-black/20 sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-4 text-xs"><span className="font-semibold uppercase tracking-[0.16em] text-slate-500">{isDemo ? 'Pages demo mode' : 'Live BFF mode'}</span><span className={`rounded-full px-2.5 py-1 font-medium ${isDemo ? 'bg-sky-400/10 text-sky-300' : 'bg-emerald-400/10 text-emerald-300'}`}>{isDemo ? 'Interactive preview' : 'Connected'}</span></div><QuoteForm onSubmit={(payload) => quoteMutation.mutate(payload)} isPending={quoteMutation.isPending} /><div className="border-t border-white/10 pt-6"><QuoteResult quote={quoteMutation.data} error={quoteMutation.error} isPending={quoteMutation.isPending} /></div></div>
        </section>
        <section className="mt-16 border-t border-white/10 pt-10" aria-labelledby="architecture-title"><div className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">System map</p><h2 id="architecture-title" className="mt-3 text-3xl font-semibold text-white">One request, two trusted boundaries.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">The browser talks to the BFF. Only the BFF can reach the vendor with its private credential.</p></div><div className="architecture-diagram" role="img" aria-label="Browser connects to React UI, React UI connects to FastAPI BFF, and FastAPI BFF connects to the authenticated mock vendor API"><div className="architecture-node"><span className="architecture-kicker">Client</span><strong>Browser</strong><small>Staff workflow</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-accent"><span className="architecture-kicker">Frontend</span><strong>React UI</strong><small>Form + query state</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-accent"><span className="architecture-kicker">BFF :8000</span><strong>FastAPI</strong><small>Validation + secret</small></div><span className="architecture-arrow" aria-hidden="true">-&gt;</span><div className="architecture-node architecture-node-vendor"><span className="architecture-kicker">Vendor :8001</span><strong>Mock API</strong><small>Quote calculation</small></div></div><p className="mt-4 text-center font-mono text-xs text-slate-500">api-key travels only between FastAPI and the vendor</p></section>
        <section className="mt-20 border-t border-white/10 pt-10"><div className="grid gap-8 md:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">How it works</p><h2 className="mt-3 text-3xl font-semibold text-white">A small system with a clear boundary.</h2></div><div className="grid gap-4 sm:grid-cols-3"><div className="info-block"><span className="info-number">01</span><h3>React UI</h3><p>Captures loan details and presents each request state with an accessible, responsive interface.</p></div><div className="info-block"><span className="info-number">02</span><h3>FastAPI BFF</h3><p>Validates requests, protects the vendor key, and translates vendor failures for the browser.</p></div><div className="info-block"><span className="info-number">03</span><h3>Mock vendor</h3><p>Calculates deterministic rates while simulating authentication and intermittent outages.</p></div></div></div></section>
        <section className="mt-20 border-t border-white/10 pt-10" aria-labelledby="adr-title"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Architecture decisions</p><h2 id="adr-title" className="mt-3 text-3xl font-semibold text-white">Why this shape?</h2><p className="mt-3 max-w-2xl leading-7 text-slate-400">These lightweight ADRs record the context, choice, benefits, and trade-offs behind the service.</p></div><div className="grid gap-4 md:grid-cols-2"><article className="adr-card"><div className="flex items-center justify-between"><span className="adr-id">ADR-001</span><span className="adr-status">Accepted</span></div><h3>FastAPI backend-for-frontend</h3><p>Protects the vendor API key, validates requests, and gives the browser one stable contract.</p><small>Trade-off: one additional network hop and a second backend process.</small></article><article className="adr-card"><div className="flex items-center justify-between"><span className="adr-id">ADR-002</span><span className="adr-status">Accepted</span></div><h3>React, Tailwind, and TanStack Query</h3><p>Provides clear component ownership, responsive styling, and explicit request lifecycle states.</p><small>Trade-off: a frontend build step and more dependencies than plain JavaScript.</small></article><article className="adr-card"><div className="flex items-center justify-between"><span className="adr-id">ADR-003</span><span className="adr-status">Accepted</span></div><h3>Bun with Vite</h3><p>Offers fast installs, a quick development loop, and a small static deployment artifact.</p><small>Trade-off: contributors need Bun as well as Python for the full stack.</small></article><article className="adr-card"><div className="flex items-center justify-between"><span className="adr-id">ADR-004</span><span className="adr-status">Accepted</span></div><h3>Separate mock vendor service</h3><p>Exercises the real integration boundary, including authentication, timeouts, and upstream failures.</p><small>Trade-off: local development requires an additional service process.</small></article><article className="adr-card md:col-span-2"><div className="flex items-center justify-between"><span className="adr-id">ADR-005</span><span className="adr-status">Accepted</span></div><h3>GitHub Pages with an optional demo mode</h3><p>Publishes an interactive static UI while keeping the production API key inside the separately hosted BFF.</p><small>Trade-off: Pages demo mode uses a client-side calculation and does not replace the live authenticated flow.</small></article></div></section>
      </div>
    </main>
  )
}
